### ISSUE TITLE
Resolve 'Gem Load Error is: undefined method `desc' for main:Object'

### ISSUE THREAD

**Issue by febeling** [bleonard/rails_stats#6]
Usage with Rails 5.1 is not quite straightforward, for me.

In order to avoid the gem load error mentioned, I had to use

```
gem 'rails_stats', require: false # instead of just gem 'rails_stats'
```

and put a manual loading into the Rakefile

```
require 'rails_stats'
```

Might be worth adding to the README.

**Comment by bleonard** [comment]
Interesting. Not sure why, but happy to merge a PR if you have README suggestions.

**Comment by febeling** [comment]
I saw the problem linked to the release of rake 11.0.0 ([9 Mar 2016](https://github.com/ruby/rake/releases/tag/v11.0.0)), but didn't confirm this myself.

**Comment by febeling** [comment]
@bleonard different from what I said first, it's probably more appropriate to apply this change and fix the underlying cause. Have a look and let me know what you think.
